allowBuilds:
  sharp: true
  "@parcel/watcher": false
  "@tailwindcss/oxide": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

blockExoticSubdeps: false

overrides:
  nuxt: https://pkg.pr.new/nuxt@26f09f7
  "@nuxt/kit": https://pkg.pr.new/@nuxt/kit@26f09f7
  "@nuxt/nitro-server": https://pkg.pr.new/@nuxt/nitro-server@26f09f7
  "@nuxt/rspack-builder": https://pkg.pr.new/@nuxt/rspack-builder@26f09f7
  "@nuxt/schema": https://pkg.pr.new/@nuxt/schema@26f09f7
  "@nuxt/vite-builder": https://pkg.pr.new/@nuxt/vite-builder@26f09f7
